# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K6M5rnvjcL-8AC7DDNV0bfpnCaJMOLV6
"""

import os
import zipfile
import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt
from scipy.stats import norm


# QUESTION 1
print("Starting Question 1")

# Define the zip file name and the target extraction directory
base_dir = os.path.dirname(os.path.abspath(__file__))
zip_name = os.path.join(base_dir, "27d1328a9d866c8330c411a3a9e5b517314b8bea.zip")
extract_dir = base_dir

# If the expected zip file is not present, use the first zip found in the project folder.
if not os.path.exists(zip_name):
    zip_candidates = glob.glob(os.path.join(base_dir, "*.zip"))
    if zip_candidates:
        zip_name = zip_candidates[0]
        print(f"Using zip file '{os.path.basename(zip_name)}' found in the project directory.")
    else:
        print(f"'{os.path.basename(zip_name)}' not found. Please ensure the zip file is uploaded.")


# Question 1a: Load and Clean Data
print("\n Question 1a")

crime_df = pd.DataFrame(columns=['Month', 'Location', 'LSOA name', 'Crime type'])

if os.path.exists(zip_name):
    try:
        with zipfile.ZipFile(zip_name, "r") as zip_ref:
            zip_ref.extractall(extract_dir)
        print(f"Zip file extracted to '{extract_dir}'.")
    except Exception as e:
        print(f"Could not extract zip file: {e}")
else:
    print(f"'{zip_name}' not found. Please ensure the zip file is uploaded.")

df_list = []

for year_month_dir in glob.glob(os.path.join(extract_dir, '[0-9][0-9][0-9][0-9]-[0-9][0-9]')):
    for file in glob.glob(os.path.join(year_month_dir, '*.csv')):
        try:
            df_list.append(pd.read_csv(file))
        except Exception as e:
            print(f"Warning: Could not read {file}: {e}")

if not df_list:
    print("Error: No CSV files found in the extracted content.")
else:
    df = pd.concat(df_list, ignore_index=True)
    cols_to_keep = ["Month", "Location", "LSOA name", "Crime type"]

    if all(col in df.columns for col in cols_to_keep):
        crime_df = df[cols_to_keep]
        print("\n--- Q1a Results ---")
        print(crime_df.head())
        print("\nUnique months loaded:", crime_df["Month"].unique())
        print("\nTotal rows:", len(df))
        print("Data loaded and cleaned successfully.")
    else:
        print("Error: The loaded CSV files are missing one of the required columns.")
        print(f"Required: {cols_to_keep}")
        print(f"Found: {list(df.columns)}")


# Question 1b: Crime Types and Locations
print("\n Question 1b")

if not crime_df.empty:
    all_crime_types = crime_df['Crime type'].dropna().unique()
    print("\nDifferent types of crime in the dataset:")
    for crime in all_crime_types:
        print(f"- {crime}")

    asb_df = crime_df[crime_df['Crime type'] == 'Anti-social behaviour']
    if not asb_df.empty:
        top_asb_counts = asb_df['LSOA name'].value_counts()
        top_asb = top_asb_counts.index[0]
        count_asb = top_asb_counts.iloc[0]
        print(f"\nLSOA with most Anti-social behaviour: {top_asb} ({count_asb} incidents)")
    else:
        print("No 'Anti-social behaviour' crimes found.")

    june_df = crime_df[crime_df['Month'] == '2024-06']
    bike_df = june_df[june_df['Crime type'] == 'Bicycle theft']
    if not bike_df.empty:
        top_bike_counts = bike_df['LSOA name'].value_counts()
        top_bike = top_bike_counts.index[0]
        count_bike = top_bike_counts.iloc[0]
        print(f"LSOA with most Bicycle theft in June 2024: {top_bike} ({count_bike} incidents)")
    else:
        print("No 'Bicycle theft' crimes found in June 2024.")
else:
    print("No data available to analyze.")


# Question 1c: Graphs and Summary Statistics
print("\n Question 1c")

if not crime_df.empty:
    crimes_over_time = crime_df.groupby('Month').size()
    crimes_over_time.index = pd.to_datetime(crimes_over_time.index)
    crimes_over_time = crimes_over_time.sort_index()

    plt.figure(figsize=(10, 5))
    plt.plot(crimes_over_time.index, crimes_over_time.values, marker='o', linestyle='-')
    plt.title('Total Crime Incidents Over Time (Aug 2023 - Jul 2025)')
    plt.xlabel('Month')
    plt.ylabel('Number of Incidents')
    plt.grid(True, axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig('q1c_graph1_time.png')
    print("\nGraph 1 (q1c_graph1_time.png) saved.")

    plt.figure(figsize=(10, 8))
    crime_counts = crime_df['Crime type'].value_counts()
    crime_counts_sorted = crime_counts.iloc[::-1]
    plt.barh(crime_counts_sorted.index, crime_counts_sorted.values)
    plt.title('Total Incidents by Crime Type (Aug 2023 - Jul 2025)')
    plt.xlabel('Number of Incidents (Log Scale)')
    plt.ylabel('Crime Type')
    plt.xscale('log')
    plt.tight_layout()
    plt.savefig('q1c_graph2_crime_types.png')
    print("Graph 2 (q1c_graph2_crime_types.png) saved.")

    print("\nInterpretation of Graphs:")
    print("1. The line graph shows that total reported crime fluctuates monthly, with notable dips around the start of 2024 and 2025, suggesting possible seasonal effects.")
    print("2. The bar chart confirms that 'Anti-social behaviour' and 'Violence and sexual offences' are by far the most reported crime categories in this dataset.")

    crimes_per_lsoa = crime_df.groupby('LSOA name').size().dropna()
    if not crimes_per_lsoa.empty:
        mean_val = crimes_per_lsoa.mean()
        median_val = crimes_per_lsoa.median()
        std_val = crimes_per_lsoa.std()
        min_val = crimes_per_lsoa.min()
        max_val = crimes_per_lsoa.max()
        q1_val = crimes_per_lsoa.quantile(0.25)
        q3_val = crimes_per_lsoa.quantile(0.75)

        print("\n--- Summary Statistics for 'Total Crimes per LSOA' ---")
        print(f"Mean: {mean_val:.2f}")
        print(f"Median: {median_val:.2f}")
        print(f"Std Dev: {std_val:.2f}")
        print(f"Range: {max_val - min_val:.2f} (Min: {min_val}, Max: {max_val})")
        print(f"Q1: {q1_val:.2f}")
        print(f"Q3: {q3_val:.2f}")
        print(f"IQR: {q3_val - q1_val:.2f}")

        print("\nExplanation of Statistics for a Layperson:")
        print(f"1. We looked at the total number of crimes for each small neighbourhood (LSOA).")
        print(f"2. The median (middle value) was {median_val:.0f} crimes — half of the neighbourhoods had more, half had less.")
        print(f"3. The mean (average) was {mean_val:.0f}, much higher than the median, showing that a few areas have very high crime counts.")
        print(f"4. The range (from {min_val} to {max_val} crimes) is wide, meaning crime levels vary greatly across London.")
    else:
        print("No crime data per LSOA to calculate summary statistics.")
else:
    print("Skipping Q1c because data was not loaded.")


# Question 1f: Confidence Interval
print("\n Question 1f")

if not crime_df.empty:
    counts = crime_df['Location'].value_counts()
    target = counts[(counts >= 200) & (counts <= 500)]

    if not target.empty:
        loc = target.index[0]
        n = target.iloc[0]
        loc_df = crime_df[crime_df['Location'] == loc]
        x = (loc_df['Crime type'] == 'Other theft').sum()
        p_hat = x / n

        z = norm.ppf(0.975)
        se = np.sqrt((p_hat * (1 - p_hat)) / n + 1e-9)
        moe = z * se
        lower, upper = max(0, p_hat - moe), min(1, p_hat + moe)

        print(f"Selected location: '{loc}'")
        print(f"Total reported crimes (n): {n}")
        print(f"Number of 'Other theft' crimes (x): {x}")
        print(f"Sample proportion (p̂): {p_hat:.4f}")
        print(f"95% Confidence Interval: ({lower:.4f}, {upper:.4f})")

        print("\nExplanation for an Expert:")
        print(f"1. To compute the 95% confidence interval for the population proportion π of 'Other theft' crimes, we used the normal approximation to the binomial distribution (sample size n = {n}).")
        print(f"2. The interval was calculated as p̂ ± zα/2 * sqrt[p̂(1−p̂)/n], where p̂ = {p_hat:.4f} and z = {z:.2f}, giving a 95% CI of ({lower:.4f}, {upper:.4f}).")
    else:
        print("No location found with 200–500 total crimes.")
else:
    print("Skipping confidence interval due to missing data.")

print(" Question 2")

def q2_user_guide():
    print("""
Knowledge Representation Guide:
- Representation used: Triples list (subject, predicate, object) - a simple relational/triple-store.
- Features: Easy to read, simple to extend, flexible. Allows representing hierarchical and associative facts.
- Limitations: only knows facts stated, cannot perform logical reasoning, can be inefficient for complex queries.
- Searching: simple pattern-matching over triples, e.g. match subject/relation/object.
""")

print("\n Question 2b")
knowledge = [
    ("Alan Turing", "isa", "Person"),
    ("Alan Turing", "field", "Computer Science"),
    ("Computer Science", "subfieldOf", "STEM"),
    ("Machine Learning", "subfieldOf", "Artificial Intelligence"),
    ("Artificial Intelligence", "subfieldOf", "Computer Science"),
    ("STEM", "subfieldOf", "Academia"),
    ("LLM", "subfieldOf", "Artificial Intelligence"),
    # Additional triples (10)
    ("Python", "isA", "Programming Language"),
    ("Python", "usedFor", "Machine Learning"),
    ("Problem solving", "doneBy", "Artificial Intelligence"),
    ("GPT4", "isA", "LLM"),
    ("Mathematics", "subfieldOf", "STEM"),
    ("Science", "subfieldOf", "STEM"),
    ("Engineering", "subfieldOf", "STEM"),
    ("Data Science", "subfieldOf", "Computer Science"),
    ("Alan Turing", "isA", "Computer Scientist"),
    ("Turing Test", "proposedBy", "Alan Turing"),
]


print("\n Question 2c")
def query(triples, subject=None, relation=None, object=None):
    """
    Return a list of triples that match the provided pattern.
    None acts as wildcard for subject/predicate/object.
    Example: query(knowledge, subject="Alan Turing") -> returns triples where subject matches.
    """
    results = []
    for (s,r,o) in triples:
        if subject is not None and s != subject:
            continue
        if relation is not None and r != relation:
            continue
        if object is not None and o != object:
            continue
        results.append((s,r,o))
    return results
q2_user_guide()
print(query(knowledge, subject = "Alan Turing"))
print(query(knowledge, object = "Artificial Intelligence"))

# Question 3
import numpy as np

weights = np.array([0.2, 0.4, 0.3, 0.6, 0.2])  # w1..w5

def perceive(x):
    """
    x: array-like of length 5 (numbers)
    Returns 0 if dot(weights,x) < 1 else 1
    """
    x_arr = np.array(x, dtype=float)
    if x_arr.shape[0] != 5:
        raise ValueError("Input must be length 5.")
    s = np.dot(weights, x_arr)
    return 1 if s >= 1.0  else 0
print(perceive([0.2, 0.3, 0.1, 0.5, 0.2]))
print(perceive([0.5, 0.5, 0.1, 1, 1]))

print("\n Question 3b")
print("User Guide:")
print("1. The 'knowledge' in this model is represented by the weights (w1–w5).")
print("   Each weight shows how strongly an input influences the output.")
print("2. This knowledge is not symbolic — it is numerical and learned through training data.")
print("3. The perceptron learns its weights by adjusting them based on errors during training.")